name: Continuous Integration (macOS only)

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - 'doc/**'
      - 'contrib/**'
      - '**/*.md'

jobs:
  build-macos:
    name: x86_64-macos

    env:
      MAKEJOBS: "-j3"
      SDK_URL: https://depends.dogecoincore.org

    runs-on: ubuntu-24.04
    container:
      image: ubuntu:22.04

    steps:
      - name: Configure container
        run: |
          ln -snf /usr/share/zoneinfo/Etc/UTC /etc/localtime
          echo Etc/UTC > /etc/timezone
          uname -a

      - name: Install packages
        run: |
          apt-get update
          apt-get install -y build-essential libtool autotools-dev automake \
               pkg-config bsdmainutils curl ca-certificates ccache rsync git \
               procps bison python3 python3-pip cmake imagemagick libcap-dev \
               librsvg2-bin libz-dev libbz2-dev libtiff-tools libtinfo5 xorriso

      - name: Checkout
        uses: actions/checkout@v4

      - name: SDK cache
        uses: actions/cache@v4
        with:
          path: ./depends/sdk-sources
          key: x86_64-macos-sdk-${{ hashFiles('.github/workflows/ci.yml') }}

      - name: Install SDK
        env:
          sdk-filename: MacOSX10.11.sdk.tar.gz
          sdk-shasum: "bec9d089ebf2e2dd59b1a811a38ec78ebd5da18cbbcd6ab39d1e59f64ac5033f"
        run: |
          mkdir -p ./depends/sdk-sources ./depends/SDKs
          echo "${{ env.sdk-shasum }}  depends/sdk-sources/${{ env.sdk-filename }}" | sha256sum -c || \
            curl --location --fail $SDK_URL/${{ env.sdk-filename }} -o depends/sdk-sources/${{ env.sdk-filename }}
          tar -C depends/SDKs -xf depends/sdk-sources/${{ env.sdk-filename }}

      - name: Dependency cache
        uses: actions/cache@v4
        with:
          path: ./depends/built
          key: x86_64-macos-depends-${{ hashFiles('depends/packages/*', '.github/workflows/ci.yml') }}

      - name: Build depends
        run: |
          make $MAKEJOBS -C depends HOST=x86_64-apple-darwin11

      - name: CCache setup
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: x86_64-macos-ccache-${{ hashFiles('**/configure.ac', '.github/workflows/ci.yml') }}

      - name: Build Dogecoin
        run: |
          depends/x86_64-apple-darwin11/native/bin/ccache --max-size=100M
          ./autogen.sh
          ./configure --prefix=`pwd`/depends/x86_64-apple-darwin11 --with-gui=qt5 --disable-tests --enable-reduce-exports
          make $MAKEJOBS deploy

      - name: Check security
        run: make -C src check-security

      - name: Cleanup qa artifacts
        run: |
          rm -rf qa/cache || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dogecoin-${{ github.sha }}-x86_64-macos
          path: |
            dist/Dogecoin-Qt.app